### ISSUE TITLE
Sha1 moved from std.crypto to std.crypto.hash

### ISSUE THREAD

**Issue by archaistvolts** [truemedian/wz#3]
wz fails to build with latest zig master download (0.6.0+243b5c7a8).  this happens when building fengb's zigbot9001 which is on commit 35b40b4.  but it looks like latest hasn't been fixed either https://github.com/truemedian/wz/blob/master/src/base/client.zig#L11

```sh
./lib/wz/src/base/client.zig:12:24: error: container 'std.crypto' has no member called 'Sha1'
const Sha1 = std.crypto.Sha1;
                       ^
./lib/wz/src/base/client.zig:35:16: note: referenced here
    var hash = Sha1.init();
```
